### PR TITLE
Close snap channel when PR is closed

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Review by Saviq — APPROVED** [review]
It would really be nice to be able to share more of this…

bors merge

**Comment by AlanGriffiths** [comment]
I wonder what bors is doing?

**Comment by AlanGriffiths** [comment]
bors retry

**Comment by AlanGriffiths** [comment]
> It would really be nice to be able to share more of this…

Yes indeed!

```
$ find CLionProjects/ -name snap.yml | wc -l
16
```

**Pull request merged**
