### PR TITLE
ci: build multi-arch

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
@Saviq is this how a timeout manifests?

**Comment by Saviq** [comment]
> @Saviq is this how a timeout manifests?

Yeah if it's cancelled you see this at the top:
>  failed Aug 22, 2023 in 44m 59s

And the "44m 59s" is within a couple seconds from the timeout.

**Comment by Saviq** [comment]
@AlanGriffiths one last one when you have a moment. Thanks!

**Review by AlanGriffiths — APPROVED** [review]
Really? The last one?

**Pull request merged**
