### PR TITLE
flutter-app: vendor in, run standalone

### PR DESCRIPTION
**Pull request by Saviq**
Fixes #78

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Why should this be vendored in instead of being a regular separate repo?

**Comment by Saviq** [comment]
> Why should this be vendored in instead of being a regular separate repo?

Because it's a test app, only usable in the context of testing Mir compositors, no need to proliferate repos.

**Comment by Conan-Kudo** [comment]
Okay, but keep in mind that I can't build this in Fedora (nor can Debian build this), so we still need test applications that don't rely on Dart and Flutter.

**Comment by Saviq** [comment]
> Okay, but keep in mind that I can't build this in Fedora (nor can Debian build this), so we still need test applications that don't rely on Dart and Flutter.

Yeah this high level of tests is not something you should generally need there. We'll still extend the headless/unit/wlcs tests of course.

**Comment by hbatagelo** [comment]
Flutter's UI is not rendered, although the application accepts user input and the mir-shell windows work as expected.

On miriway:
image

FWIW, I also get the black screen with LIBGL_ALWAYS_SOFTWARE=1

**Comment by Saviq** [comment]
> Flutter's UI is not rendered, although the application accepts user input and the mir-shell windows work as expected.

Was a preexisting problem (#80). Fixed now.

Only remaining issue, but not relevant here, is:
- https://github.com/canonical/mir/issues/3393

**Review by hbatagelo — APPROVED** [review]
Looks good.

**Pull request merged**
